version: "3.1"

services:
  hackernews-dev:
    build:
      context: ./backend
      target: dev
    command: make dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./backend/:/go/src/backend
    ports:
      - "8080:8080"
    networks:
      - docker-network

  hackernews-frontend-dev:
    build:
      context: ./frontend
      target: dev
    command: make dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./frontend/:/node/src/frontend
    ports:
      - "8000:8000"
    networks:
      - docker-network

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    volumes:
      - hackernews-postgres-dev:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - docker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "hackernews"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  docker-network:
    driver: bridge

volumes:
  hackernews-postgres-dev:
