version: "3.1"

services:
  hackernews:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - $HTTPS_SSL/fullchain.pem:/etc/letsencrypt/live/vps.osac.org.np/fullchain.pem
      - $HTTPS_SSL/privkey.pem:/etc/letsencrypt/live/vps.osac.org.np/privkey.pem
    ports:
      - "8008:8080"
    networks:
      - docker-network

  hackernews-frontend:
    build: ./frontend
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./frontend/:/node/src/frontend
      - $HTTPS_SSL/fullchain.pem:/etc/letsencrypt/live/vps.osac.org.np/fullchain.pem
      - $HTTPS_SSL/privkey.pem:/etc/letsencrypt/live/vps.osac.org.np/privkey.pem
    env_file:
      - ./.env
    ports:
      - "80:443"
      - "9000:443"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
