version: "3.1"

services:
  hackernews:
    build: ./backend
    image: hackernews:0.0.1
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8008:8080"
    networks:
      - docker-network

  hackernews-frontend:
    build: ./frontend
    image: hackernews-frontend:0.0.1
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "9000:80"
    networks:
      - docker-network

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - docker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "hackernews"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  docker-network:
    driver: bridge
