// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token *string `json:"token"`
	User  *User   `json:"user"`
}

type Link struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	PostedBy    *User  `json:"postedBy"`
	URL         string `json:"url"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewLink struct {
	Description string `json:"description"`
	URL         string `json:"url"`
}

type NewUser struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Email    *string `json:"email"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Email    *string `json:"email"`
}
