apiVersion: v1
kind: Service
metadata:
  name: { { .ServiceName } }
  labels:
    app: { { .ServiceName } }
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: { { .ServiceName } }
